/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AboutUs: typeof import('./src/components/AboutUs.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    LandingPage: typeof import('./src/components/LandingPage.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader.vue')['default']
    Projects: typeof import('./src/components/Projects.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
