/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Footer: typeof import('./src/components/Footer.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Hero: typeof import('./src/components/Hero.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    Project: typeof import('./src/components/project/Project.vue')['default']
    Projects: typeof import('./src/components/Projects.vue')['default']
    WhoAreWe: typeof import('./src/components/WhoAreWe.vue')['default']
  }
}
