name: CI/CD for the website and development
run-name: ${{ github.actor }} ran this workflow.

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: build
        run: yarn install && yarn build
      - name: deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PCSW_WEBSITE_F6380 }}
          channelId: live
          projectId: pcsw-website-f6380
